import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useCompanyId } from '@/features/auth/hooks/useAuth'
import { projectsApi } from '@/features/projects/api/projects.api'
import { invoicesApi } from '@/features/invoices/api/invoices.api'
import { useToast } from '@/shared/hooks/useToast'
import type { Project } from '@/entities/project/model'

const projectKeys = { all: ['projects'] as const, list: (companyId: string) => [...projectKeys.all, companyId] as const }
export function useProjects() { const companyId = useCompanyId(); return useQuery({ queryKey: projectKeys.list(companyId), queryFn: () => projectsApi.list(companyId), enabled: companyId !== 'demo-company' }) }
export function useCreateProject() { const companyId = useCompanyId(); const qc = useQueryClient(); const toast = useToast(); return useMutation({ mutationFn: projectsApi.create, onSuccess: () => { qc.invalidateQueries({ queryKey: projectKeys.list(companyId) }); qc.invalidateQueries({ queryKey: ['dashboard', companyId] }); toast.success('Projekt utworzony') } }) }
export function useCreateProjectFromEstimate() { const companyId = useCompanyId(); const qc = useQueryClient(); const toast = useToast(); return useMutation({ mutationFn: (estimateId: string) => projectsApi.createFromEstimate(companyId, estimateId), onSuccess: () => { qc.invalidateQueries({ queryKey: projectKeys.list(companyId) }); qc.invalidateQueries({ queryKey: ['dashboard', companyId] }); toast.success('Projekt utworzony z kosztorysu') }, onError: (error) => toast.error('Nie udało się utworzyć projektu', error instanceof Error ? error.message : undefined) }) }
export function useUpdateProject() { const companyId = useCompanyId(); const qc = useQueryClient(); const toast = useToast(); return useMutation({ mutationFn: ({ id, input }: { id: string; input: Partial<Project> }) => projectsApi.update(id, input, companyId), onSuccess: () => { qc.invalidateQueries({ queryKey: projectKeys.list(companyId) }); qc.invalidateQueries({ queryKey: ['dashboard', companyId] }); toast.success('Projekt zaktualizowany') } }) }
export function useUpdateProjectStatus() { const companyId = useCompanyId(); const qc = useQueryClient(); const toast = useToast(); return useMutation({ mutationFn: ({ id, status }: { id: string; status: Project['status'] }) => projectsApi.updateStatus(id, status), onSuccess: () => { qc.invalidateQueries({ queryKey: projectKeys.list(companyId) }); qc.invalidateQueries({ queryKey: ['dashboard', companyId] }); toast.info('Status projektu zaktualizowany') } }) }
export function useCreateInvoiceFromProject() { const companyId = useCompanyId(); const qc = useQueryClient(); const toast = useToast(); return useMutation({ mutationFn: (projectId: string) => invoicesApi.createFromProject(companyId, projectId), onSuccess: () => { qc.invalidateQueries({ queryKey: ['invoices', companyId] }); qc.invalidateQueries({ queryKey: ['dashboard', companyId] }); toast.success('Faktura wygenerowana z projektu') }, onError: (error) => toast.error('Nie udało się wygenerować faktury', error instanceof Error ? error.message : undefined) }) }
export function useDeleteProject() { const companyId = useCompanyId(); const qc = useQueryClient(); const toast = useToast(); return useMutation({ mutationFn: (id: string) => projectsApi.delete(id), onSuccess: () => { qc.invalidateQueries({ queryKey: projectKeys.list(companyId) }); qc.invalidateQueries({ queryKey: ['dashboard', companyId] }); toast.info('Projekt usunięty') } }) }
