import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useCompanyId } from '@/features/auth/hooks/useAuth'
import { invoicesApi } from '@/features/invoices/api/invoices.api'
import { useToast } from '@/shared/hooks/useToast'
import type { Invoice } from '@/entities/invoice/model'

const invoiceKeys = { all: ['invoices'] as const, list: (companyId: string) => [...invoiceKeys.all, companyId] as const }
export function useInvoices() { const companyId = useCompanyId(); return useQuery({ queryKey: invoiceKeys.list(companyId), queryFn: () => invoicesApi.list(companyId), enabled: companyId !== 'demo-company' }) }
export function useCreateInvoice() { const companyId = useCompanyId(); const qc = useQueryClient(); const toast = useToast(); return useMutation({ mutationFn: invoicesApi.create, onSuccess: () => { qc.invalidateQueries({ queryKey: invoiceKeys.list(companyId) }); qc.invalidateQueries({ queryKey: ['dashboard', companyId] }); toast.success('Faktura utworzona') }, onError: (error) => toast.error('Nie udało się utworzyć faktury', error instanceof Error ? error.message : undefined) }) }
export function useUpdateInvoice() { const companyId = useCompanyId(); const qc = useQueryClient(); const toast = useToast(); return useMutation({ mutationFn: ({ id, input }: { id: string; input: Partial<Invoice> }) => invoicesApi.update(id, input, companyId), onSuccess: () => { qc.invalidateQueries({ queryKey: invoiceKeys.list(companyId) }); toast.success('Faktura zaktualizowana') } }) }
export function useDeleteInvoice() { const companyId = useCompanyId(); const qc = useQueryClient(); const toast = useToast(); return useMutation({ mutationFn: (id: string) => invoicesApi.delete(id), onSuccess: () => { qc.invalidateQueries({ queryKey: invoiceKeys.list(companyId) }); qc.invalidateQueries({ queryKey: ['dashboard', companyId] }); toast.info('Faktura usunięta') } }) }
export function useMarkInvoicePaid() { const companyId = useCompanyId(); const qc = useQueryClient(); const toast = useToast(); return useMutation({ mutationFn: (id: string) => invoicesApi.markPaid(id), onSuccess: () => { qc.invalidateQueries({ queryKey: invoiceKeys.list(companyId) }); qc.invalidateQueries({ queryKey: ['dashboard', companyId] }); toast.success('Faktura oznaczona jako opłacona') } }) }
export function useSendInvoiceToKsef() { const companyId = useCompanyId(); const qc = useQueryClient(); const toast = useToast(); return useMutation({ mutationFn: (id: string) => invoicesApi.sendToKsef(id), onSuccess: () => { qc.invalidateQueries({ queryKey: invoiceKeys.list(companyId) }); toast.success('Faktura wysłana do KSeF') } }) }
export function useCreateInvoiceFromEstimate() { const companyId = useCompanyId(); const qc = useQueryClient(); const toast = useToast(); return useMutation({ mutationFn: (estimateId: string) => invoicesApi.createFromEstimate(companyId, estimateId), onSuccess: () => { qc.invalidateQueries({ queryKey: invoiceKeys.list(companyId) }); qc.invalidateQueries({ queryKey: ['dashboard', companyId] }); toast.success('Faktura wygenerowana z kosztorysu') }, onError: (error) => toast.error('Nie udało się wygenerować faktury', error instanceof Error ? error.message : undefined) }) }
